### ISSUE TITLE
AttributeError: 'str' object has no attribute 'copy'

### ISSUE THREAD

**Issue by Denubis** [wragge/troveharvester#1]
Invoking troveharvester, with a fresh pyenv:
`$ troveharvester start "https://api.trove.nla.gov.au/v2/result?zone=newspaper&q=%22Brian%22%" [key removed] --pdf --text`

produces:

```                    
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.5/envs/troveharvester-3.7.5/bin/troveharvester", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/.pyenv/versions/3.7.5/envs/troveharvester-3.7.5/lib/python3.7/site-packages/troveharvester/__main__.py", line 550, in main
    prepare_harvest(args)
  File "/home/ubuntu/.pyenv/versions/3.7.5/envs/troveharvester-3.7.5/lib/python3.7/site-packages/troveharvester/__main__.py", line 521, in prepare_harvest
    start_harvest(data_dir=data_dir, key=args.key, query=args.query, pdf=args.pdf, text=args.text, start='*', max=args.max)
  File "/home/ubuntu/.pyenv/versions/3.7.5/envs/troveharvester-3.7.5/lib/python3.7/site-packages/troveharvester/__main__.py", line 531, in start_harvest
    harvester = Harvester(query_params=params, data_dir=data_dir, pdf=pdf, text=text, start=start, max=max)
  File "/home/ubuntu/.pyenv/versions/3.7.5/envs/troveharvester-3.7.5/lib/python3.7/site-packages/troveharvester/__main__.py", line 81, in __init__
    self._get_total()
  File "/home/ubuntu/.pyenv/versions/3.7.5/envs/troveharvester-3.7.5/lib/python3.7/site-packages/troveharvester/__main__.py", line 84, in _get_total
    params = self.query_params.copy()
AttributeError: 'str' object has no attribute 'copy'
```

Is there a issue with 3.7? (Happy to help replicate further)

Ubuntu 16.04, Python 3.7.5, dedicated pyenv. Freshly reregistered API key

**Comment by wragge** [comment]
Ah, thanks for letting me know. Seems like the error is in parsing API urls because it works fine if you use a url from the web interface, eg this will work (and produce the same results):

```
troveharvester start "https://trove.nla.gov.au/newspaper/result?q=%22Brian%22" [key removed] --pdf --text
```
I'll look into it further.

**Comment by Denubis** [comment]
Just to continue documenting stuff (sorry, was alt-tabbed)

Tested in 2.7.17 (which is now EOL)

```
buntu@brian:/data/trove27$ python --version
Python 2.7.17
ubuntu@brian:/data/trove27$ pip install troveharvester
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting troveharvester
  Downloading troveharvester-0.2.2.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/.pyenv/versions/2.7.17/envs/troveharvester27-2.7.17/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/tmp/pip-install-Ik7G_8/troveharvester/setup.py'"'"'; __file__='"'"'/mnt/tmp/pip-install-Ik7G_8/troveharvester/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /mnt/tmp/pip-install-Ik7G_8/troveharvester/pip-egg-info
         cwd: /mnt/tmp/pip-install-Ik7G_8/troveharvester/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/tmp/pip-install-Ik7G_8/troveharvester/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
1 ubuntu@brian:/data/trove27$ pip install --upgrade troveharvester
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting troveharvester
  Using cached troveharvester-0.2.2.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/.pyenv/versions/2.7.17/envs/troveharvester27-2.7.17/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/tmp/pip-install-gXsVc8/troveharvester/setup.py'"'"'; __file__='"'"'/mnt/tmp/pip-install-gXsVc8/troveharvester/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /mnt/tmp/pip-install-gXsVc8/troveharvester/pip-egg-info
         cwd: /mnt/tmp/pip-install-gXsVc8/troveharvester/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/tmp/pip-install-gXsVc8/troveharvester/setup.py", line 6, in <module>
        with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
"Can't install" -- not going to debug further on 2.7 

Thanks for the suggestion on the prior API url. My run last year used them and I was spooked into the change with v2. Will test now on 3.8.1

**Comment by Denubis** [comment]
Adding notes. None of the v2 syntax works on the web interface based queries. (the new date specification, decade facets, etc) My intuition is saying this is a newspaper specific thing, because the facets *do* show up for book-zone queries...

**Comment by Denubis** [comment]
I confirm the mitigation of the web URL works. Thank you muchly!
`"https://trove.nla.gov.au/newspaper/result?q=&exactPhrase=${searchTerm}&anyWords=&notWords=&requestHandler=&dateFrom=1970-01-01&dateTo=1980-12-31&sortby="` is what I'm using in my shell script.

**Comment by wragge** [comment]
> None of the v2 syntax works on the web interface based queries. 

Yes, there are a number of differences in the parameters used between the web interface and the API. If you give the Newspaper harvester a url from a search in the web interface it will attempt to translate the parameters into ones that the API understands.

If you want to use API specific features, then you can feed the Harvester an API query. These queries should have been passed through with minimal processing, but I realised that I hadn't updated this part of the code when I changed the harvester to use version 2 of the API. That's why you were getting an error.

This is now fixed, so both web and API queries should work as expected. Let me know if there's any further problems.
